import { Link } from 'react-router-dom'

export function SkillCard({ skill, onAdd, disabled = false }) { return <article className={`card skill-card accent-${skill.accent || 'mint'}`}><div className="card-kicker">{skill.category}</div><h3>{skill.title}</h3><p>{skill.level}</p><div className="card-row"><span>{skill.teachers} students can teach</span>{onAdd && <button className="icon-button" onClick={onAdd} disabled={disabled} aria-label={`${skill.level === 'Available to add' ? 'Add' : 'Remove'} ${skill.title}`}>{skill.level === 'Available to add' ? '+' : 'x'}</button>}</div></article> }

export function CourseCard({ course, onEnroll, enrolled, onEdit }) { return <article className="card course-card"><div className="course-icon">{course.skill.slice(0, 2).toUpperCase()}</div><div className="card-kicker">{course.skill} · {course.category || 'General'}</div><h3>{course.title}</h3><p>{course.description}</p><div className="meta-row"><span>{course.level}</span><span>{course.duration}</span></div><small>{course.instructor || 'Campus Exchange'} · ★ {Number(course.rating || 0).toFixed(1)} · {course.enrollment_count || 0} enrolled</small>{onEnroll && <button className="button button-outline" onClick={onEnroll} disabled={enrolled}>{enrolled ? 'Enrolled' : 'Enroll now'}</button>}{onEdit && <button className="text-button" onClick={onEdit}>Edit course</button>}</article> }

export function StudentCard({ student }) { return <article className="card student-card"><div className="person"><span className="avatar avatar-large">{student.initials}</span><div><h3>{student.name}</h3><p>{student.course}</p></div></div><p className="availability">{student.availability}</p><div className="tag-row"><span className="tag">Teaches {student.teaches}</span>{student.wants ? <span className="tag tag-soft">Learns {student.wants}</span> : <span className="tag tag-soft">One-way teaching match</span>}</div><Link className="button button-outline full-width" to="/matching">Open matching</Link></article> }

export function MatchCard({ student, onRequest, requesting = false }) { return <article className="card match-card"><div className="match-label">{student.match_type === 'reciprocal' ? 'Reciprocal exchange' : 'One-way teaching match'}</div><div className="match-people"><div className="person"><span className="avatar">{student.initials}</span><div><h3>{student.name}</h3><p>{student.course}</p></div></div><div className="exchange-arrow">↔</div><div className="match-skills"><strong>Can teach {student.teaches}</strong><span>{student.wants ? `Wants to learn ${student.wants}` : 'No reciprocal skill listed'}</span></div></div><div className="card-actions"><button className="button button-dark" onClick={onRequest} disabled={requesting}>{requesting ? 'Sending...' : 'Send request'}</button></div></article> }

export function RequestCard({ request, onUpdate }) { return <article className="request-row"><div><strong>{request.skill}</strong><span>{request.partner}</span></div><span className={`status status-${request.status.toLowerCase()}`}>{request.status}</span><span className="request-date">{request.date}</span><div className="request-actions">{request.status === 'Pending' && onUpdate && <><button className="text-button success" onClick={() => onUpdate('accepted')}>Accept</button><button className="text-button danger" onClick={() => onUpdate('rejected')}>Reject</button></>}{request.status === 'Accepted' && onUpdate && <button className="text-button success" onClick={() => onUpdate('completed')}>Complete</button>}</div></article> }

export function ProgressCard({ title, progress, lessons, quiz, onAdvance }) { return <article className="card progress-card"><div className="card-row"><div><div className="card-kicker">Enrolled course</div><h3>{title}</h3></div><strong className="progress-value">{progress}%</strong></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="card-row progress-meta"><span>{lessons} lessons completed</span><span>{quiz}</span>{onAdvance && <button className="text-button" onClick={onAdvance}>Complete lesson</button>}</div></article> }

export function ReviewCard({ name, initials, rating, review }) { return <article className="card review-card"><div className="person"><span className="avatar">{initials}</span><div><h3>{name}</h3><span className="stars">{'★'.repeat(rating)}<span>{'★'.repeat(5 - rating)}</span></span></div></div><p>“{review}”</p></article> }
