import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { CourseCard, SkillCard } from '../components/Cards'
import { api } from '../services/api'

const pillars = [['01', 'Create your profile', 'Tell the campus what you know, what you are learning, and where you want to grow.'], ['02', 'Add your skills', 'Choose the skills you can teach and the skills you want to learn from others.'], ['03', 'Find your match', 'Meet students whose skills complete your learning goals and interests.'], ['04', 'Exchange and review', 'Learn, teach, log progress, and leave useful feedback after every exchange.']]

export default function Home() {
  const [stats, setStats] = useState(null)
  useEffect(() => { api.publicStats().then(setStats).catch(() => setStats(null)) }, [])
  const featuredSkills = stats?.featured_skills || []
  return <>
    <section className="hero"><div className="hero-copy"><div className="eyebrow">Student-powered learning community</div><h1>Learn something.<br /><em>Teach something.</em><br />Grow together.</h1><p className="hero-text">Campus Exchange helps students swap knowledge, build confidence, and make learning feel less like a solo assignment.</p><div className="hero-actions"><Link to="/register" className="button button-dark">Join platform <span>↗</span></Link><Link to="/skills" className="button button-light">Explore skills</Link></div><div className="hero-proof"><span className="avatar-stack"><i>AM</i><i>DN</i><i>KR</i></span><span><strong>{stats?.total_students ?? '—'}</strong> students learning together</span></div></div><div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-note note-one">Your next skill<br /><strong>is closer than you think.</strong></div><div className="hero-note note-two"><span className="tiny-dot" /> {stats?.total_completed_exchanges ?? 0} completed exchanges</div><div className="hero-card"><span className="hero-card-label">Today’s exchange</span><h3>Learn ↔ Teach</h3><p>One campus, many possibilities</p><div className="hero-card-line"><span /><span /></div></div><div className="hero-initials">CS</div></div></section>
    <section className="marquee"><span>LEARN</span><b>✦</b><span>TEACH</span><b>✦</b><span>EXCHANGE</span><b>✦</b><span>LEARN</span><b>✦</b><span>TEACH</span></section>
    <section className="home-section"><div className="stat-strip home-stats"><div><strong>{stats?.total_students ?? '—'}</strong><span>Students</span></div><div><strong>{stats?.total_skills ?? '—'}</strong><span>Skills</span></div><div><strong>{stats?.total_courses ?? '—'}</strong><span>Courses</span></div><div><strong>{stats?.total_completed_exchanges ?? '—'}</strong><span>Completed exchanges</span></div></div></section>
    <section className="home-section" id="how-it-works"><div className="section-heading"><div><div className="eyebrow">One campus, many possibilities</div><h2>Make your curiosity<br /><em>useful.</em></h2></div><p className="heading-aside">A connected space for the skills you are building, the ones you can share, and the people who can help you move forward.</p></div><div className="pillar-grid">{pillars.map(([number, title, text]) => <article className="pillar" key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p><i>↗</i></article>)}</div></section>
    <section className="home-section tinted"><div className="section-heading"><div><div className="eyebrow">Browse the community</div><h2>What could you<br /><em>learn next?</em></h2></div><Link to="/skills" className="text-link">See all skills ↗</Link></div><div className="card-grid three">{featuredSkills.length ? featuredSkills.slice(0, 3).map(skill => <SkillCard key={skill.id} skill={{ title: skill.name, category: skill.category, level: `${skill.can_teach_count} can teach · ${skill.wants_to_learn_count} want to learn`, teachers: skill.can_teach_count }} />) : <p className="empty-state">Skills will appear here as the campus library grows.</p>}</div></section>
    <section className="home-section"><div className="section-heading"><div><div className="eyebrow">Micro-learning library</div><h2>Small lessons.<br /><em>Real progress.</em></h2></div><Link to="/courses" className="text-link">Browse courses ↗</Link></div><div className="card-grid three">{stats?.featured_courses?.map(course => <CourseCard key={course.id} course={course} enrolled={false} />)}</div></section>
    <section className="home-section tinted home-cta"><div><div className="eyebrow">Your next exchange starts here</div><h2>Bring what you know.<br /><em>Find what’s next.</em></h2><p>Create a real profile connected to the campus database.</p></div><Link to="/register" className="button button-dark">Join platform <span>↗</span></Link></section>
  </>
}